Algoritmo "Estrutura repetitiva enquanto' "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/23/2026
Var
 x,soma : real

Inicio
      Escreval("Digite o primeiro número")
      leia(x)
      soma <- x
      enquanto x <> 0 faca
               Escreval("Digite outro número")
               leia(x)
               soma <- (soma + x)
      fimenquanto
      Escreval("O resultado da soma é: ", soma)

Fimalgoritmo