Algoritmo "Media_ponderada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/27/2026
Var
   x, i, num  : real
   T : real


Inicio
      escreval("Digite o numero: ")
      leia(num)
      leia(x)
      leia(i)
      
      T <- (((num * 3) + (x * 2) + (i)))/ 6)
      escreval("Média Ponderada: ", T:2:1)

Fimalgoritmo