Algoritmo "Multiplos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/20/2026
Var
 x,y : Inteiro


Inicio
      Escreval("Digite dois valores que quer consultar: ")
      leia(x)
      leia(y)
      se (x % y = 0) ou (y % x  = 0) entao
         Escreval("Seus números são multiplos!")
      senao
           escreval("Seus Valores não são multiplos!")
      Fimse

Fimalgoritmo