Algoritmo "Senhas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/6/2026
Var
   password , try : inteiro

Inicio
      escreval("Digite a senha do programa: ")
      leia(Password)
      Repita
      escreval("Digite sua senha: ")
      leia(try)
      ate  try = password
      escreval("Senha correta")

Fimalgoritmo