Algoritmo "Tabuada utiilizando estrutura repetitiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/26/2026
Var
N, T, I : inteiro


Inicio
escreva("Digite o numeral em que quer a tabuada")
leia(N)
escreva("DIgite A quantidade de valores que quer :")
leia(T)
       para i de 0 ate T faça
            Escreval(N," X ", I, "= ",(N*I))
       fimpara

Fimalgoritmo